Metrics/LineLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Metrics/AbcSize:
    Enabled: false
Style/EmptyMethod:
    Enabled: false
Style/SymbolArray:
    Enabled: false
Style/Documentation:
    Enabled: false
Style/RegexpLiteral:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false

AllCops:
    Exclude:
        - 'db/**/*'
        - 'bin/**/*'
        - 'config/**/*'
        - 'mailers/**/*'
        - 'test/**/*'
